name: consulin_mobile_dev
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  http: ^1.2.2
  google_fonts: ^6.2.1
  multi_dropdown: ^3.0.1
  file_picker: ^8.1.4
  fluttertoast: ^8.2.8
  syncfusion_flutter_charts: ^27.2.2
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
